// =========================================================================
// DATOS REALISTAS INICIALES (MOCK & SEED DATA) - GALINDO BARBER ICA
// =========================================================================

import { Producto, Categoria, Curso, Alumno, Matricula, CajaChica, MovimientoCaja, MovimientoInventario } from '@/types/database';

export const MOCK_CATEGORIAS: Categoria[] = [
  { id: 'cat-1', nombre: 'Máquinas de Corte (Clippers)', slug: 'maquinas-corte', orden: 1, activo: true },
  { id: 'cat-2', nombre: 'Patilleras y Trimmers', slug: 'patilleras-trimmers', orden: 2, activo: true },
  { id: 'cat-3', nombre: 'Afeitadoras (Shavers)', slug: 'afeitadoras-shavers', orden: 3, activo: true },
  { id: 'cat-4', nombre: 'Tijeras & Navajas', slug: 'tijeras-navajas', orden: 4, activo: true },
  { id: 'cat-5', nombre: 'Pomadas, Ceras y Químicos', slug: 'pomadas-ceras-quimicos', orden: 5, activo: true },
  { id: 'cat-6', nombre: 'Accesorios & Capas', slug: 'accesorios-capas', orden: 6, activo: true },
  { id: 'cat-7', nombre: 'Kits para Alumnos', slug: 'kits-alumnos', orden: 7, activo: true },
];

export const MOCK_PRODUCTOS: Producto[] = [
  {
    id: 'prod-1',
    sku: 'WAHL-MC-CORDLESS',
    nombre: 'Wahl Magic Clip Cordless 5 Estrellas Edición Gold',
    slug: 'wahl-magic-clip-cordless-gold',
    categoria_id: 'cat-1',
    descripcion: 'La máquina de degradado preferida por barberos profesionales. Cuchilla Stagger-Tooth con dientes escalonados para un fade suave y sin marcas. Motor rotativo de 6,800 RPM y batería de litio de 100 minutos.',
    especificaciones: {
      'Motor': 'Rotativo 6,800 RPM',
      'Batería': 'Iones de litio (100 min)',
      'Cuchilla': 'Stagger-Tooth Crunch Blade revestida de titanio',
      'Peso': '290 gramos',
    },
    precio_compra: 380.00,
    precio_venta: 480.00,
    precio_alumno: 440.00, // Descuento para alumnos Galindo
    stock: 8,
    stock_minimo: 3,
    imagenes: ['https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=800&q=80'],
    destacado: true,
    en_oferta: true,
    precio_oferta: 460.00,
    activo: true,
    creado_en: '2026-09-01T10:00:00Z',
    actualizado_en: '2026-09-10T12:00:00Z',
  },
  {
    id: 'prod-2',
    sku: 'BBL-SKELETON-FX',
    nombre: 'BaBylissPRO BlackFX Skeleton Trimmer',
    slug: 'babyliss-pro-blackfx-skeleton-trimmer',
    categoria_id: 'cat-2',
    descripcion: 'Detalladora con cuchilla expuesta en 360° para una visión total al perfilar barba y contornos. Cuchilla DLC / Titanio de corte al ras cero gap ajustable. Motor diseñado por Ferrari de 7,200 RPM.',
    especificaciones: {
      'Motor': 'Ferrari Brushless 7,200 RPM',
      'Cuchilla': 'T-Blade 360° DLC Deep Tooth',
      'Autonomía': '2 horas continuas',
      'Carcasa': 'Metálica antideslizante',
    },
    precio_compra: 420.00,
    precio_venta: 540.00,
    precio_alumno: 495.00,
    stock: 5,
    stock_minimo: 2,
    imagenes: ['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80'],
    destacado: true,
    en_oferta: false,
    activo: true,
    creado_en: '2026-09-02T10:00:00Z',
    actualizado_en: '2026-09-02T10:00:00Z',
  },
  {
    id: 'prod-3',
    sku: 'SHAVER-ANDIS-PRO',
    nombre: 'Andis ProFoil Lithium Plus Titanium Shaver',
    slug: 'andis-profoil-lithium-plus-shaver',
    categoria_id: 'cat-3',
    descripcion: 'Afeitadora finalizadora de doble lámina dorada hipoalergénica. Ideal para desvanecidos limpios sin irritación ni encarnación de vello.',
    precio_compra: 220.00,
    precio_venta: 290.00,
    precio_alumno: 260.00,
    stock: 2, // Alerta de stock bajo
    stock_minimo: 3,
    imagenes: ['https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=800&q=80'],
    destacado: true,
    en_oferta: false,
    activo: true,
    creado_en: '2026-09-05T10:00:00Z',
    actualizado_en: '2026-09-05T10:00:00Z',
  },
  {
    id: 'prod-4',
    sku: 'TIJERA-MATSUZAKI-6',
    nombre: 'Set Tijeras Profesionales Galindo Master (Corte + Pulir 6.0")',
    slug: 'set-tijeras-profesionales-galindo-master',
    categoria_id: 'cat-4',
    descripcion: 'Acero japonés 440C de alta dureza. Incluye una tijera de corte de filo dulce y una tijera de entresacar de 30 dientes ergonómica con estuche de cuero.',
    precio_compra: 130.00,
    precio_venta: 195.00,
    precio_alumno: 170.00,
    stock: 12,
    stock_minimo: 4,
    imagenes: ['https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=800&q=80'],
    destacado: false,
    en_oferta: false,
    activo: true,
    creado_en: '2026-09-06T10:00:00Z',
    actualizado_en: '2026-09-06T10:00:00Z',
  },
  {
    id: 'prod-5',
    sku: 'POMADA-SUAVECITO-ORIG',
    nombre: 'Pomada Suavecito Original Hold 4oz (Fijación Media)',
    slug: 'pomada-suavecito-original-hold-4oz',
    categoria_id: 'cat-5',
    descripcion: 'Base de agua, aroma característico masculino tradicional. Brillo medio y fijación duradera que se retira fácilmente con agua.',
    precio_compra: 38.00,
    precio_venta: 55.00,
    precio_alumno: 48.00,
    stock: 35,
    stock_minimo: 10,
    imagenes: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80'],
    destacado: true,
    en_oferta: true,
    precio_oferta: 50.00,
    activo: true,
    creado_en: '2026-09-07T10:00:00Z',
    actualizado_en: '2026-09-07T10:00:00Z',
  },
  {
    id: 'prod-6',
    sku: 'KIT-ALUMNO-INICIAL',
    nombre: 'Kit Oficial del Estudiante Galindo Academy (Básico)',
    slug: 'kit-oficial-estudiante-galindo-basico',
    categoria_id: 'cat-7',
    descripcion: 'Todo lo indispensable para el primer día de clases en la academia. Incluye: Capa Galindo impermeable antiestática, 3 peines de corte de carbono, cepillo fade bieldo, atomizador continuo, papel cuello y navajera de acero inoxidable.',
    precio_compra: 95.00,
    precio_venta: 160.00,
    precio_alumno: 130.00,
    stock: 15,
    stock_minimo: 5,
    imagenes: ['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80'],
    destacado: true,
    en_oferta: false,
    activo: true,
    creado_en: '2026-09-08T10:00:00Z',
    actualizado_en: '2026-09-08T10:00:00Z',
  },
];

export const MOCK_CURSOS: Curso[] = [
  {
    id: 'curso-1',
    titulo: 'Barbería Integral & Fade Profesional',
    slug: 'barberia-integral-fade-profesional',
    descripcion_corta: 'Aprende desde cero todas las técnicas de corte masculino: tijera, máquina, visagismo, afeitado clásico de toalla caliente y desvanecidos de alta precisión.',
    temario_detallado: [
      'Ergonomía del barbero y bioseguridad en Ica',
      'Manejo de máquinas (palanca abierta, intermedia y cerrada)',
      'Técnicas de Low Fade, Mid Fade y High Fade',
      'Geometría capilar y corte con tijera recta y de entresacar',
      'Ritual de afeitado con toalla caliente, vapor y navaja libre',
      'Diseño, perfilado y tinturado de barba',
      'Atención al cliente de alto valor y fotos para redes sociales',
    ],
    duracion_semanas: 12,
    horas_academicas: 90,
    costo_matricula: 80.00,
    costo_mensualidad: 250.00,
    costo_total_contado: 750.00,
    incluye_kit: true,
    descripcion_kit: 'Incluye capa oficial Galindo, peine de carbono, bieldo talquero y manual impreso.',
    imagen_url: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    activo: true,
    sede: 'ica',
  },
  {
    id: 'curso-2',
    titulo: 'Masterclass: Fade Avanzado, Freestyle & Colorimetría',
    slug: 'masterclass-fade-avanzado-freestyle',
    descripcion_corta: 'Diseñado para barberos con experiencia que buscan dominar técnicas de competencia: Skin fade al milímetro, figuras con navaja y platinados extremos.',
    temario_detallado: [
      'Skin Fade y Taper Fade de nivel competición',
      'Líneas freestyle, degradé en figuras y geometría urbana',
      'Decoloración capilar sin maltratar la fibra capilar',
      'Matización de tonos plata, blanco nórdico y pasteles',
      'Técnicas de styling y fotografía profesional para Instagram/TikTok',
    ],
    duracion_semanas: 6,
    horas_academicas: 45,
    costo_matricula: 60.00,
    costo_mensualidad: 280.00,
    costo_total_contado: 580.00,
    incluye_kit: false,
    imagen_url: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=800&q=80',
    activo: true,
    sede: 'ica',
  },
  {
    id: 'curso-hyo-barber',
    titulo: 'Barbería Profesional & Fade',
    slug: 'barberia-profesional-fade-huancayo',
    descripcion_corta: 'Formación técnica en barbería en Sede Huancayo (Jr. Guido 654). Contamos con 4 opciones flexibles para que elijas en cuánto tiempo deseas terminar con modelos reales.',
    temario_detallado: [
      'Historia de la barbería y bioseguridad en Sede Huancayo',
      'Conocimiento de materiales, herramientas y productos',
      'Manejo de máquinas Clipper, Trimmer y Shaver (palancas y calibración)',
      'Técnicas de degradado Fade (Low Fade, Mid Fade, High Fade)',
      'Geometría capilar y corte con tijera recta y de entresacar',
      'Ritual de afeitado clásico con toalla caliente y navaja',
      'Diseño, visagismo y perfilado de barba',
      'Prácticas intensivas en modelos reales provistos por la escuela',
      'Atención al cliente de alto valor y fotos para redes sociales',
    ],
    duracion_semanas: 8,
    horas_academicas: 60,
    costo_matricula: 80.00,
    costo_mensualidad: 599.00,
    costo_total_contado: 1100.00,
    incluye_kit: true,
    descripcion_kit: 'Incluye capa oficial Galindo, peines de corte, bieldo talquero y manual impreso.',
    imagen_url: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&w=800&q=80',
    activo: true,
    sede: 'huancayo',
    turnos: [
      {
        id: 'HYO-BARBER-OP1',
        nombre: 'Opción 1 — Acelerado (2 Meses)',
        horario: '8:30 AM - 11:30 AM / 1:00 PM - 3:45 PM / 4:00 PM - 7:00 PM / 7:00 PM - 9:30 PM',
        dias: '5 Veces x semana (De Lunes a Viernes)',
        duracion_meses: 2,
        costo_mensualidad: 599.00,
        vacantesDisponibles: 5,
      },
      {
        id: 'HYO-BARBER-OP2',
        nombre: 'Opción 2 — Intermedio (3 Meses)',
        horario: '8:30 AM - 11:30 AM / 1:00 PM - 3:45 PM / 4:00 PM - 7:00 PM / 7:00 PM - 9:30 PM',
        dias: '3 Días x semana (Lunes, Miércoles y Viernes)',
        duracion_meses: 3,
        costo_mensualidad: 499.00,
        vacantesDisponibles: 6,
      },
      {
        id: 'HYO-BARBER-OP3',
        nombre: 'Opción 3 — Flexible (4 Meses)',
        horario: '8:30 AM - 11:30 AM / 1:00 PM - 3:45 PM / 4:00 PM - 7:00 PM / 7:00 PM - 9:30 PM',
        dias: '2 Días a la semana (Lunes y Miércoles)',
        duracion_meses: 4,
        costo_mensualidad: 399.00,
        vacantesDisponibles: 8,
      },
      {
        id: 'HYO-BARBER-OP4',
        nombre: 'Opción 4 — Solo Sábados (4 Meses)',
        horario: 'Mañana: 9:00 AM - 1:00 PM  o  Tarde: 4:00 PM - 8:00 PM',
        dias: '1 Vez a la semana (Solo Sábados)',
        duracion_meses: 4,
        costo_mensualidad: 499.00,
        vacantesDisponibles: 4,
      },
    ],
  },
  {
    id: 'curso-hyo-tattoo',
    titulo: 'Curso Profesional de Tatuaje (Galindo Tattoo Studio)',
    slug: 'curso-tatuaje-galindo-huancayo',
    descripcion_corta: '¡Aprende el arte que deja huella! Formación desde cero o perfeccionamiento con docentes profesionales en Jr. Guido 654, Huancayo. Materiales básicos incluidos y prácticas en piel sintética y lienzo real.',
    temario_detallado: [
      'Historia del Tatuaje y bioseguridad en el estudio',
      'Conocimiento y esterilización de materiales',
      'Armado y desinfección adecuada de mesa de trabajo',
      'Conocimiento y calibración de máquina de bobina y rotativa',
      'Conocimiento de Agujas, Cartuchos, Varillas y Fuentes de poder',
      'Conocimientos de tipos de piel y ergonomía del tatuador',
      'Dinámica de dibujo, líneas, encaje y diseño tipográfico',
      'Prácticas guiadas de calcado y colocación de Stencil',
      'Dominio de pulso y profundidad en piel sintética',
      'Práctica de tatuaje minimalista en fruta y piel sintética',
      'Técnicas de sombras, difuminado y puntillismo (Whip Shading / Dotwork)',
      'Práctica de tatuaje acuarelado y aplicación de color',
      'Presentación de proyecto final en lienzo real — Graduación',
    ],
    duracion_semanas: 12,
    horas_academicas: 90,
    costo_matricula: 80.00,
    costo_mensualidad: 550.00,
    costo_total_contado: 1500.00,
    incluye_kit: true,
    descripcion_kit: 'Materiales básicos incluidos para prácticas en clase (tintas, agujas, piel sintética y bioseguridad).',
    imagen_url: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=800&q=80',
    activo: true,
    sede: 'huancayo',
    turnos: [
      {
        id: 'HYO-TATTOO-OP1',
        nombre: 'Opción 1 — Intensivo (3 Meses)',
        horario: 'Turnos a elegir: Mañana (9:00 AM - 12:00 PM) / Tarde (3:00 PM - 6:00 PM)',
        dias: '5 Días x semana (De Lunes a Viernes)',
        duracion_meses: 3,
        costo_mensualidad: 550.00,
        vacantesDisponibles: 4,
      },
      {
        id: 'HYO-TATTOO-OP2',
        nombre: 'Opción 2 — Regular (4 Meses)',
        horario: 'Turnos a elegir: Mañana (9:00 AM - 12:00 PM) / Tarde (3:00 PM - 6:00 PM)',
        dias: '3 Días x semana (L-M-M / Lunes, Miércoles y Viernes)',
        duracion_meses: 4,
        costo_mensualidad: 499.00,
        vacantesDisponibles: 6,
      },
      {
        id: 'HYO-TATTOO-OP3',
        nombre: 'Opción 3 — Flexible (5 Meses)',
        horario: 'Turnos a elegir: Mañana (9:00 AM - 12:00 PM) / Tarde (3:00 PM - 6:00 PM)',
        dias: '2 Días x semana (Lunes y Miércoles)',
        duracion_meses: 5,
        costo_mensualidad: 399.00,
        vacantesDisponibles: 6,
      },
    ],
  },
];

export const MOCK_ALUMNOS: Alumno[] = [
  {
    id: 'alum-1',
    dni: '74829103',
    nombres: 'Carlos Daniel',
    apellidos: 'Mendoza Flores',
    celular: '956321487',
    email: 'carlos.mendoza@gmail.com',
    distrito: 'Ica Centro',
    creado_en: '2026-08-15T14:30:00Z',
  },
  {
    id: 'alum-2',
    dni: '71938204',
    nombres: 'Brayan Alexis',
    apellidos: 'Gómez Palomino',
    celular: '956874123',
    email: 'brayan.barber@gmail.com',
    distrito: 'Parcona',
    creado_en: '2026-08-20T10:15:00Z',
  },
  {
    id: 'alum-3',
    dni: '76543219',
    nombres: 'Junior Enrique',
    apellidos: 'Salas Huamán',
    celular: '956112233',
    email: 'junior.salas@hotmail.com',
    distrito: 'Subtanjalla',
    creado_en: '2026-09-01T09:00:00Z',
  },
];

export const MOCK_MATRICULAS: Matricula[] = [
  {
    id: 'mat-1',
    codigo_matricula: 'MAT-2026-0101',
    alumno_id: 'alum-1',
    alumno: MOCK_ALUMNOS[0],
    curso_id: 'curso-1',
    curso: MOCK_CURSOS[0],
    horario_id: 'hor-1',
    horario: {
      id: 'hor-1',
      curso_id: 'curso-1',
      sede: 'Sede Principal Ica',
      turno: 'MANANA',
      dias: 'Lunes, Miércoles y Viernes',
      hora_inicio: '09:00',
      hora_fin: '12:00',
      fecha_inicio: '2026-09-01',
      fecha_fin: '2026-11-24',
      cupos_totales: 15,
      cupos_ocupados: 12,
      activo: true,
    },
    fecha_matricula: '2026-08-28',
    estado: 'EN_CURSO',
    monto_matricula_pagado: 80.00,
    total_curso: 750.00,
    saldo_pendiente: 250.00,
    kit_entregado: true,
    cuotas: [
      {
        id: 'cuota-1',
        matricula_id: 'mat-1',
        numero_cuota: 1,
        monto: 250.00,
        fecha_vencimiento: '2026-09-01',
        fecha_pago: '2026-08-30',
        estado: 'PAGADA',
        metodo_pago: 'YAPE',
        numero_operacion: 'YAPE-849201',
      },
      {
        id: 'cuota-2',
        matricula_id: 'mat-1',
        numero_cuota: 2,
        monto: 250.00,
        fecha_vencimiento: '2026-10-01',
        estado: 'PENDIENTE',
      },
      {
        id: 'cuota-3',
        matricula_id: 'mat-1',
        numero_cuota: 3,
        monto: 250.00,
        fecha_vencimiento: '2026-11-01',
        estado: 'PENDIENTE',
      },
    ],
  },
  {
    id: 'mat-2',
    codigo_matricula: 'MAT-2026-0102',
    alumno_id: 'alum-2',
    alumno: MOCK_ALUMNOS[1],
    curso_id: 'curso-1',
    curso: MOCK_CURSOS[0],
    horario_id: 'hor-1',
    fecha_matricula: '2026-08-29',
    estado: 'EN_CURSO',
    monto_matricula_pagado: 80.00,
    total_curso: 750.00,
    saldo_pendiente: 500.00,
    kit_entregado: true,
    cuotas: [
      {
        id: 'cuota-4',
        matricula_id: 'mat-2',
        numero_cuota: 1,
        monto: 250.00,
        fecha_vencimiento: '2026-09-01',
        estado: 'VENCIDA', // Alumno con cuota vencida para mostrar alerta
      },
    ],
  },
];

export const MOCK_CAJA_ACTUAL: CajaChica = {
  id: 'caja-hoy',
  sede: 'Sede Central Ica - Calle Bolívar',
  usuario_apertura_id: 'usr-admin',
  usuario_apertura_nombre: 'Diego Galindo',
  fecha_apertura: '2026-09-16T08:30:00Z',
  monto_apertura: 150.00, // Efectivo inicial en caja
  total_ingresos_efectivo: 480.00,
  total_ingresos_digital: 850.00, // Yape / Plin / Transferencias
  total_egresos_efectivo: 45.00,  // Compra de agua y desinfectante
  saldo_teorico_efectivo: 585.00, // 150 + 480 - 45
  estado: 'ABIERTA',
};

export const MOCK_MOVIMIENTOS_CAJA: MovimientoCaja[] = [
  {
    id: 'mov-1',
    caja_id: 'caja-hoy',
    tipo: 'INGRESO_VENTA',
    monto: 480.00,
    metodo_pago: 'EFECTIVO',
    concepto: 'Venta Mostrador #0042 - Wahl Magic Clip Gold',
    referencia_id: 'PED-0042',
    usuario_id: 'usr-admin',
    usuario_nombre: 'Diego Galindo',
    fecha: '2026-09-16T10:15:00Z',
  },
  {
    id: 'mov-2',
    caja_id: 'caja-hoy',
    tipo: 'INGRESO_MATRICULA',
    monto: 330.00,
    metodo_pago: 'YAPE',
    concepto: 'Matrícula + Cuota 1 Alumno Carlos Mendoza (Fade Pro)',
    referencia_id: 'MAT-2026-0101',
    usuario_id: 'usr-admin',
    usuario_nombre: 'Diego Galindo',
    fecha: '2026-09-16T11:40:00Z',
  },
  {
    id: 'mov-3',
    caja_id: 'caja-hoy',
    tipo: 'EGRESO_GASTO',
    monto: 45.00,
    metodo_pago: 'EFECTIVO',
    concepto: 'Compra de botellón de agua y toallas de papel descartables',
    categoria_gasto: 'INSUMOS_CLASE',
    usuario_id: 'usr-admin',
    usuario_nombre: 'Diego Galindo',
    fecha: '2026-09-16T13:10:00Z',
  },
];

export const MOCK_MOVIMIENTOS_INVENTARIO: MovimientoInventario[] = [
  {
    id: 'inv-1',
    producto_id: 'prod-1',
    tipo: 'ENTRADA',
    cantidad: 10,
    stock_anterior: 0,
    stock_nuevo: 10,
    motivo: 'Compra inicial distribuidor oficial Wahl Perú',
    usuario_id: 'usr-admin',
    usuario_nombre: 'Diego Galindo',
    fecha: '2026-09-01T09:00:00Z',
  },
  {
    id: 'inv-2',
    producto_id: 'prod-1',
    tipo: 'SALIDA',
    cantidad: 1,
    stock_anterior: 10,
    stock_nuevo: 9,
    motivo: 'Venta en tienda #0012',
    usuario_id: 'usr-admin',
    usuario_nombre: 'Diego Galindo',
    fecha: '2026-09-05T15:30:00Z',
  },
  {
    id: 'inv-3',
    producto_id: 'prod-1',
    tipo: 'SALIDA',
    cantidad: 1,
    stock_anterior: 9,
    stock_nuevo: 8,
    motivo: 'Venta Ticket Mostrador #0042',
    usuario_id: 'usr-admin',
    usuario_nombre: 'Diego Galindo',
    fecha: '2026-09-16T10:15:00Z',
  },
];
